### ISSUE TITLE
I dont see scripts on ae 2021

### ISSUE THREAD

**Issue by 4stacks67** [otomad/om_midi#17]
is there another way to put the script to ae 2021?

**Comment by otomad** [comment]
## Install

Download the latest script files.

### `om midi.jsx`

Placed in the Scripts\ScriptUI Panels folder located in the After Effects installation directory.

> (ie. C:\Program Files\Adobe\Adobe After Effects 2023\Scripts\ScriptUI Panels)

**Comment by 4stacks67** [comment]
Also can i use multiple videos on the script?

**Comment by 4stacks67** [comment]
> ## Install
> Download the latest script files.
> 
> ### `om midi.jsx`
> Placed in the Scripts\ScriptUI Panels folder located in the After Effects installation directory.
> 
> > (ie. C:\Program Files\Adobe\Adobe After Effects 2023\Scripts\ScriptUI Panels)

i use adobe animate 2021

**Comment by Evauation** [comment]
You can't use om_midi with Adobe Animate... They're 2 completely different programs.

**Comment by 4stacks67** [comment]
> You can't use om_midi with Adobe Animate... They're 2 completely different programs.

i meant ae 2021, sorry

**Comment by Evauation** [comment]
> ## Install
> 
> Download the latest script files.
> ### `om midi.jsx`
> 
> Placed in the Scripts\ScriptUI Panels folder located in the After Effects installation directory.
> 
> > (ie. C:\Program Files\Adobe\Adobe After Effects 2023\Scripts\ScriptUI Panels)

Other options include this path
C:\Users\\[USERNAME]\AppData\Roaming\Adobe\After Effects\[VERSION]\Scripts\ScriptUI Panels

replace USERNAME with your pc's name and VERSION with the version you're using

OR

Open AE, go to file > scripts > install scriptui panel. Select the file then restart AE.

**Comment by 4stacks67** [comment]
Also, it shows a white background every time i click reply

**Comment by 4stacks67** [comment]
and i don't see it on the panel, this script is difficult

**Comment by Evauation** [comment]
> Also, it shows a white background every time i click reply

You may not have a video in your composition



> and i don't see it on the panel, this script is difficult

Did you install it cuz if you did or if you put in the script ui panels folder, you should see it here
![image](https://github.com/otomad/om_midi/assets/108847709/269b8527-e600-441f-bdde-adc4607a3683)

And to be fair, this script is made for more flexibility in mind for Adobe AE, a much more advanced program than Vegas Pro. Which means it's not as simple as its sister project, Otomad Helper.

**Comment by 4stacks67** [comment]
i did, i'm trying to put it on my library

**Comment by Evauation** [comment]
You mean dock it?

**Comment by otomad** [comment]
@4stacks67 

Please enable Edit > Preferences > Scripting & Expressions > Allow Scripts to Write Files and Access Network.

**Comment by 4stacks67** [comment]
> You mean dock it?

ye

**Comment by 4stacks67** [comment]
> @4stacks67
> 
> Please enable Edit > Preferences > Scripting & Expressions > Allow Scripts to Write Files and Access Network.

how do i dock it

**Comment by Evauation** [comment]
> > @4stacks67
> > Please enable Edit > Preferences > Scripting & Expressions > Allow Scripts to Write Files and Access Network.
> 
> how do i dock it


https://github.com/otomad/om_midi/assets/108847709/70cb6bda-aad0-4f74-901e-1805658d7995

**Comment by 4stacks67** [comment]
Also i had a video in composition and it still gives me the nulls, this is really getting difficult

**Comment by otomad** [comment]
> Also i had a video in composition and it still gives me the nulls, this is really getting difficult

change to "Effects" tab.

**Comment by 4stacks67** [comment]
ok, and audio doesnt change, just keyframes moving

**Comment by 4stacks67** [comment]
and its sped up with no keyframes

**Comment by Evauation** [comment]
Here's what you do with a video with an audio sample that's baseline at note C5

in om_midi, go to effects, select Time Remap (Truncated) or (Stretched), depending on your sample, Horizonal Flip and Tuning with Base Pitch at C5.

Then you have your visuals. Everything else you wanna do is up to you. I recommend watching some After Effects tutorials on how to use After Effects more efficiently.

@otomad's video also demonstrates how to use this script effectively. 
https://youtu.be/amDtqY_HsGM

**Comment by otomad** [comment]
> ok, and audio doesnt change, just keyframes moving

scroll to bottom, check "Tunning".

**Comment by 4stacks67** [comment]
This script is literally broken or something, the tune is wayy low and idk what happened, i'm starting to stick with otomad helper

**Comment by Evauation** [comment]
Then I can't recommend you use om_midi, you can continue to use [Otomad Helper for Vegas](https://github.com/otomad/OtomadHelper) if you find that easier. Like said before, om_midi is for after effects which is a more advanced program for advanced editors.
